### ISSUE TITLE
FA Pro icons

### ISSUE THREAD

**Issue by korhox** [ntnyq/vuepress-plugin-iconify#3]
Hello!

Does the plugin support pro icons from FontAwesome and how can I enable them?

**Comment by ntnyq** [comment]
This plugin is just a wrapper of [@iconify/vue](https://docs.iconify.design/icon-components/vue) and use icon sets data from [iconify](https://iconify.design/) which is an open source project.

All icon collections from [Website](https://icones.js.org/) is available.

But sadly, it seems that `FA Pro` is not listed.

**Comment by korhox** [comment]
Ok! Thank you for the reply!
